src/Entity/PhotoReport.php
<?php

namespace App\Entity;

use App\Repository\PhotoReportsRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=PhotoReportsRepository::class)
 */
class PhotoReport
{
    private const PUBLISHED = 1;
    private const DRAFT = 0;

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=Stock::class, inversedBy="photoReports")
     * @ORM\JoinColumn(nullable=false)
     */
    private $stock;

    /**
     * @ORM\Column(type="string", length=500)
     */
    private $title;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=500, nullable=true)
     */
    private $image;

    /**
     * @ORM\Column(type="datetime")
     */
    private $create_at;

    /**
     * @ORM\OneToMany(targetEntity=Photo::class, mappedBy="photoReport")
     */
    private $photos;

    /**
     * @ORM\Column(type="boolean")
     */
    private $is_published;

    public function __construct()
    {
        $this->photos = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getStock(): ?Stock
    {
        return $this->stock;
    }

    public function setStock(?Stock $stock): self
    {
        $this->stock = $stock;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getCreateAt(): ?\DateTimeInterface
    {
        return $this->create_at;
    }

    public function setCreateAt(\DateTimeInterface $create_at): self
    {
        $this->create_at = $create_at;

        return $this;
    }

    public function setCreateAtValue()
    {
        $this->create_at = (new \DateTime())->modify('+7 hour');
    }

    /**
     * @return Collection|Photo[]
     */
    public function getPhotos(): Collection
    {
        return $this->photos;
    }

    public function addPhoto(Photo $photo): self
    {
        if (!$this->photos->contains($photo)) {
            $this->photos[] = $photo;
            $photo->setPhotoReport($this);
        }

        return $this;
    }

    public function removePhoto(Photo $photo): self
    {
        if ($this->photos->contains($photo)) {
            $this->photos->removeElement($photo);
            // set the owning side to null (unless already changed)
            if ($photo->getPhotoReport() === $this) {
                $photo->setPhotoReport(null);
            }
        }

        return $this;
    }

    public function getIsPublished(): ?bool
    {
        return $this->is_published;
    }

    public function setIsPublished()
    {
        $this->is_published = self::PUBLISHED;
    }

    public function setIsDraft()
    {
        $this->is_published = self::DRAFT;
    }

}

src/Entity/Stock.php
<?php

namespace App\Entity;

use App\Repository\StockRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\StockRepository", repositoryClass=StockRepository::class)
 */
class Stock
{
    private const PUBLISHED = 1;
    private const DRAFT = 0;

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=500)
     */
    private $title;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=500, nullable=true)
     */
    private $image;

    /**
     * @ORM\Column(type="datetime")
     */

    private $date_start;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_end;

    /**
     * @ORM\Column(type="datetime")
     */
    private $create_at;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $update_at;

    /**
     * @ORM\OneToMany(targetEntity=Child::class, mappedBy="stock")
     */
    private $children;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $rules;

    /**
     * @ORM\OneToMany(targetEntity=PhotoReport::class, mappedBy="stock")
     */
    private $photoReports;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $thanks;

    /**
     * @ORM\Column(type="boolean")
     */
    private $is_published;

    /**
     * @ORM\ManyToOne(targetEntity=Category::class, inversedBy="stocks")
     * @ORM\JoinColumn(nullable=false)
     */
    private $category;

    public function __construct()
    {
        $this->children = new ArrayCollection();
        $this->photoReports = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getImage()
    {
        return $this->image;
    }

    public function setImage(string $image)
    {
        $this->image = $image;

        return $this;
    }

    public function getDateStart(): ?\DateTimeInterface
    {
        return $this->date_start;
    }

    public function setDateStart(\DateTimeInterface $date_start): self
    {
        $this->date_start = $date_start;

        return $this;
    }

    public function getDateEnd(): ?\DateTimeInterface
    {
        return $this->date_end;
    }

    public function setDateEnd(\DateTimeInterface $date_end): self
    {
        $this->date_end = $date_end;

        return $this;
    }

    public function getCreateAt(): ?\DateTimeInterface
    {
        return $this->create_at;
    }

    public function setCreateAt(\DateTimeInterface $create_at): self
    {
        $this->create_at = $create_at;

        return $this;
    }

    public function setCreateAtValue()
    {
        $this->create_at = (new \DateTime())->modify('+7 hour');
    }

    public function getUpdateAt(): ?\DateTimeInterface
    {
        return $this->update_at;
    }

    public function setUpdateAt(\DateTimeInterface $update_at): self
    {
        $this->update_at = $update_at;

        return $this;
    }

    public function setUpdateAtValue()
    {
        $this->update_at = (new \DateTime())->modify('+7 hour');
    }

    /**
     * @return Collection|Child[]
     */
    public function getChildren(): Collection
    {
        return $this->children;
    }

    public function addChild(Child $child): self
    {
        if (!$this->children->contains($child)) {
            $this->children[] = $child;
            $child->setStock($this);
        }

        return $this;
    }

    public function removeChild(Child $child): self
    {
        if ($this->children->contains($child)) {
            $this->children->removeElement($child);
            // set the owning side to null (unless already changed)
            if ($child->getStock() === $this) {
                $child->setStock(null);
            }
        }

        return $this;
    }

    public function getRules(): ?string
    {
        return $this->rules;
    }

    public function setRules(?string $rules): self
    {
        $this->rules = $rules;

        return $this;
    }

    /**
     * @return Collection|PhotoReport[]
     */
    public function getPhotoReports(): Collection
    {
        return $this->photoReports;
    }

    public function addPhotoReport(PhotoReport $photoReport): self
    {
        if (!$this->photoReports->contains($photoReport)) {
            $this->photoReports[] = $photoReport;
            $photoReport->setStock($this);
        }

        return $this;
    }

    public function removePhotoReport(PhotoReport $photoReport): self
    {
        if ($this->photoReports->contains($photoReport)) {
            $this->photoReports->removeElement($photoReport);
            // set the owning side to null (unless already changed)
            if ($photoReport->getStock() === $this) {
                $photoReport->setStock(null);
            }
        }

        return $this;
    }

    public function getThanks(): ?string
    {
        return $this->thanks;
    }

    public function setThanks(?string $thanks): self
    {
        $this->thanks = $thanks;

        return $this;
    }

    public function getIsPublished(): ?bool
    {
        return $this->is_published;
    }

    public function setIsPublished()
    {
        $this->is_published = self::PUBLISHED;
    }

    public function setIsDraft()
    {
        $this->is_published = self::DRAFT;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }

}

src/Form/PhotoReportType.php
<?php

namespace App\Form;

use App\Entity\PhotoReport;
use App\Entity\Stock;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\File;

class PhotoReportType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('stock', EntityType::class, array(
                'label' => 'Заголовок акции, к которой относится фотоотчет',
                'class' => Stock::class,
                'choice_label' => 'title', // какое поле из акций будет отображаться
                'disabled' => $options['is_stock_photo_report']
            ))
            ->add('title', TextType::class, array(
                'label' => 'Заголовок'
            ))
            ->add('description', TextareaType::class, array(
                'label' => 'Описание фотоотчета'
            ))
            ->add('image', FileType::class, array(
                'label' => 'Главная фотография',
                'required' => false,
                'mapped' => false,
                'constraints' => [
                    new File([
                        'maxSize' => '5000k',
                        'mimeTypes' => [
                            'image/jpeg',
                            'image/pjpeg',
                            'image/png',
                            'image/tiff'
                        ],
                        'mimeTypesMessage' => 'Доступны форматы JPEG, PNG, TIFF',
                    ])]
            ))
            ->add('save', SubmitType::class, array(
                'label' => 'Сохранить'
            ))
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => PhotoReport::class,
            'is_stock_photo_report' => false
        ]);
    }
}

src/Controller/Main/PhotoReportController.php
<?php


namespace App\Controller\Main;


use App\Entity\PhotoReport;
use App\Entity\Post;
use App\Entity\Stock;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

class PhotoReportController extends BaseController
{
    /**
     * @Route("/photoReports/", name="main_photo_reports")
     * @param int $id
     * @param Request $request
     */
    public function index( Request $request)
    {
        $photoReports = $this->getDoctrine()->getRepository(PhotoReport::class)->findAllPhotoReportsOrderByDate();

        $dateWithoutDays = (new \DateTime('now'))->modify('- 20 days');
        $newPosts = $this->getDoctrine()->getRepository(Post::class)->findNewPosts($dateWithoutDays);

        $forRender = parent::renderDefault();
        $forRender['today'] = new \DateTime('now');
        $forRender['title'] = 'Фотоотчеты';
        $forRender['photo_reports'] = $photoReports;
        $forRender['new_posts'] = $newPosts;
        return $this->render("main/photoReports/index.html.twig", $forRender);
    }
}

src/Controller/Main/StockController.php
<?php


namespace App\Controller\Main;

use App\Entity\PhotoReport;
use App\Entity\Photo;
use App\Entity\Post;
use App\Entity\Stock;
use App\Entity\Child;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;

class StockController extends BaseController
{
    /**
     * @Route("/stock/{id}", name="main_stock")
     * @param int $id
     * @param Request $request
     */
    public function index(int $id, Request $request)
    {
        $stock = $this->getDoctrine()->getRepository(Stock::class)->find($id);

        $dateWithout15Days = (new \DateTime('now'))->modify('- 20 days');
        $newPhotoReports = $this->getDoctrine()->getRepository(PhotoReport::class)->findNewPhotoReports($dateWithout15Days);

        $forRender = parent::renderDefault();
        $forRender['today'] = new \DateTime('now');
        $forRender['new_photo_reports'] = $newPhotoReports;
        $forRender['stock'] = $stock;
        return $this->render("main/stock/index.html.twig", $forRender);
    }

    /**
     * @Route("/stock/{id}/children", name="main_stock_children")
     * @param int $id
     * @param Request $request
     */
    public function showChildrens(int $id, Request $request)
    {
        $stock = $this->getDoctrine()->getRepository(Stock::class)->find($id);
        $children = $stock->getChildren();
        $institution_names = $this->getDoctrine()->getRepository(Child::class)->findInstitutionNames($id);
        $group_names = $this->getDoctrine()->getRepository(Child::class)->findGroupNames($id);

        $dateWithout15Days = (new \DateTime('now'))->modify('- 20 days');
        $newPhotoReports = $this->getDoctrine()->getRepository(PhotoReport::class)->findNewPhotoReports($dateWithout15Days);

        $user = $this->getUser();


        $forRender = parent::renderDefault();
        $forRender['stock'] = $stock;
        $forRender['children'] = $children;
        $forRender['user'] = $user;
        $forRender['institution_names'] = $institution_names;
        $forRender['new_photo_reports'] = $newPhotoReports;
        $forRender['group_names'] = $group_names;
        return $this->render("main/stock/children/index.html.twig", $forRender);
    }

    /**
     * @Route("/stock/{id}/photoReports", name="main_stock_photo_reports")
     * @param int $id
     * @param Request $request
     */
    public function showPhotoReports(int $id, Request $request)
    {
        $stock = $this->getDoctrine()->getRepository(Stock::class)->find($id);
        $photoReports = $stock->getPhotoReports();

        $dateWithoutDays = (new \DateTime('now'))->modify('- 20 days');
        $newPosts = $this->getDoctrine()->getRepository(Post::class)->findNewPosts($dateWithoutDays);

        $forRender = parent::renderDefault();
        $forRender['stock'] = $stock;
        $forRender['new_posts'] = $newPosts;
        $forRender['photo_reports'] = $photoReports;
        return $this->render("main/stock/photoReports/index.html.twig", $forRender);
    }

    /**
     * @Route("/stock/photoReports/{id}/photos", name="main_stock_photos")
     * @param int $id
     * @param Request $request
     */
    public function showPhotos(int $id, Request $request)
    {
        $photoReport = $this->getDoctrine()->getRepository(PhotoReport::class)->find($id);
        $photos = $photoReport->getPhotos();

        $dateWithoutDays = (new \DateTime('now'))->modify('- 20 days');
        $newPosts = $this->getDoctrine()->getRepository(Post::class)->findNewPosts($dateWithoutDays);

        $forRender = parent::renderDefault();
        $forRender['photo_report'] = $photoReport;
        $forRender['new_posts'] = $newPosts;
        $forRender['photos'] = $photos;
        return $this->render("main/stock/photoReports/photo/index.html.twig", $forRender);
    }


}

templates/main/stock/photoReports/index.html.twig
{% extends 'main/base.html.twig' %}

{% block title %}{{ stock.title }}{% endblock %}
{% block h1 %}{{ h1 }}{% endblock %}

{% block sidebar %}
        <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
            <div class="carousel-inner">
                {% for new_post in new_posts %}
                    {% if new_post.isPublished %}
                        {% if loop.index == 1 %}
                            <div class="carousel-item active">
                        {% else %}
                            <div class="carousel-item">
                        {% endif %}
                            <a href="{{ path('main_post', {'id': new_post.id}) }}" style="text-decoration: none!important;">
                                <img src="{{ asset('uploads/images/post/' ~ new_post.image) }}" class="d-block w-100  rounded-top" alt="{{ new_post.title }}">
                                <div class="d-none d-md-block text-center">
                                    <h5 class="orange-color rounded-bottom" >{{ new_post.title }}</h5>
                                </div>
                            </a>
                        </div>
                    {% endif %}
                {% endfor %}
            </div>
                <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
        </div>
{% endblock %}

{% block body %}
    <div class="container-fluid main-content">
        <div class="row no-gutters">
            <div class="col-12 col-lg-10 col-md-10">
                <div class="form ml-5 font-amatic">
                <h2 class="title-size m-3 ml-5 pb-3 border-bottom" style="border-width: 3px!important;
                        border-color: #fa9821!important;"><strong>Акция «{{ stock.title }}» успешно завершилась!</strong></h2>
                    <b class="date-size">{{ stock.dateStart|date('d.m.Y') }} — {{ stock.dateEnd|date('d.m.Y') }}</b>
                    <p class="pre-wrap font-open-sans description-size">{{ stock.thanks }}</p>

                    {% if photo_reports is empty %}
                        <p class="font-open-sans description-size">По мере проведения утренников ниже появятся фотоотчеты, где вы сможете посмотреть на детей,
                            которым покупали подарки и порадоваться вместе с ними!</p>
                        <img src="{{ asset('uploads/images/stock/' ~ stock.image) }}" class="mr-3 img-rounded"
                             alt="Главное фото" width="600" align="left">
                        <a href="{{ path('main_photo_reports') }}" class="btn btn-size orange-color">Фотоотчеты к другим акциям</a>
                    {% endif %}

                    {% for photo_report in photo_reports %}
                        {% if photo_report.isPublished %}
                            <h2 class="mb-3 mt-3" style="font-size: 40px;"><b>{{ photo_report.title }}</b></h2>
                            <div class="media">
                            <div>
                                <img src="{{ asset('uploads/images/photoReport/' ~ photo_report.image) }}" class="mr-3 img-rounded"
                                     alt="Главное фото" width="500" align="left">
                            </div>
                            <div class="media-body">
                                <b class="date-size">{{ photo_report.createAt|date('d.m.Y') }}</b>
                                <p class="pre-wrap part-description font-open-sans description-size">{{ photo_report.description }}</p>
                                <a href="{{ path('main_stock_photos', {'id': photo_report.id}) }}" class="btn orange-color btn-size">Подробнее</a>
                            </div>
                        </div>
                    {% endif %}
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>

{% endblock %}